name: run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
<<<<<<< HEAD
          python-version: 3.13.4
=======
          python-version: 3.12.10
>>>>>>> d584b04cc1a1b570f4f74ec9d979b121dafc7cac
      - name: Install
        run: |
          python -m pip install -e .
      - name: Run
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          python -m obisnd
